repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
