repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: ^mesa/cookiecutter-mesa/
        language_version: python3.7
      - id: black-jupyter
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
