name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: pre-commit/action@v2.0.3
    - uses: peter-evans/create-pull-request@v3
      with:
        title: "Pyupgrade to Python 3.6"
        branch: pyupgrade-36
        base: main
        commit-message: "[Bot] Pyupgrade to Python 3.6"
