name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v2.0.3
      continue-on-error: true
    - uses: peter-evans/create-pull-request@v3
      with:
        title: "Pyupgrade to Python 3.8"
        branch: pyupgrade-38
        base: main
        commit-message: "[Bot] Pyupgrade to Python 3.8"
